name: Run BYNIGHTS script

on:
  schedule:
    - cron: "30 9 * * *"   # 09:30 UTC = 10:30 CET
  workflow_dispatch:

jobs:
  run-bynights:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install
          npx playwright install --with-deps

      - name: Run BYNIGHTS script
        run: |
          npm start
